id: AC11B1C05
base_file: f5848.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:32:27.610811
  last_modified_at: 2022-05-30 18:32:27.610814
