id: AC11B1C05
base_file: f09A3.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:32:27.587904
  last_modified_at: 2022-05-30 18:32:27.587911
