id: AC11B1C05
base_file: fB6D6.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:32:27.630660
  last_modified_at: 2022-05-30 18:32:27.630663
