id: AC11B1C05
base_file: f3A0F.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:32:27.596485
  last_modified_at: 2022-05-30 18:32:27.596491
