id: AC11B1C05
base_file: f3DB6.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:32:27.600153
  last_modified_at: 2022-05-30 18:32:27.600160
