id: AC11B1C05
base_file: fC478.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:32:27.636451
  last_modified_at: 2022-05-30 18:32:27.636454
