id: AC11B1C05
base_file: f9E26.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:32:27.625148
  last_modified_at: 2022-05-30 18:32:27.625156
